### ISSUE TITLE
Organización de Github

### ISSUE THREAD

**Issue by Jhony0311** [WalterC87/weredone#1]
Sería bueno que tuvieramos una organización para poder trabajar todos bajo ese esquema como equipo. Abro un issue porque asi podemos ir creando cosas y discutirlas aqui en Github y darle algo de seguimiento. Saludos!

**Comment by wcorderolara** [comment]
Me parece genial la sugerencia Jhony, como les digo en el README esta semana estare subiendo los issues, para que por esta vía nos organicemos en equipos para poder sacar este proyecto

**Comment by patrixd** [comment]
También habría que elegir unos estándares y estilos de código. El lenguaje en el que programaremos será inglés no?

**Comment by wcorderolara** [comment]
Cuando te refieres a estándares supongo que te refieres a como haremos para nombrar variables, funciones, procedimientos, clases y todo lo demás, estilos de código sería de investigar un poco más y ver cual se nos adecua mejor para trabajar, con respecto al lenguaje en el que se programará no se si vale la pena hacerlo completamente en español pero si, la idea es hacerlo en ingles lo que se pueda y lo que no pues practicaremos el spanglish jeje

**Comment by patrixd** [comment]
Sí me refiero a eso ^^ si vamos a ser muchos y cada uno de un sitio habría que definirlos.

jaja XD Por experiencia el spanglish acaba siendo un desorden. En la empresa donde estoy se comenzó con spanglish y ahora cada uno programa como le parece, pero como más cómodos estéis, yo me adapto ;)

Por si os gustan, aquí están las guías que usa Google: https://code.google.com/p/google-styleguide/

**Comment by Jhony0311** [comment]
Estas son cosas importantes, podriamos ir abriendo issues separados e ir haciendo estas cosas. Tambien se deben comenzar a seleccionar los lenguajes a utilizar. Incluso tambien podriamos tener algunos conceptos para lo que sean ramas y demás.

**Comment by wcorderolara** [comment]
Vamos abrir diferentes branches de acuerdo a los  requerimientos y grupos de desarrollo, como veran en otros issues el lenguaje a usar sera python/django para Hacer el API REST con la estructura e iremos trabajando con Angular.js como framework frontend.

Pero quiero que estemos unos 5 al menos para definir todo

**Comment by patrixd** [comment]
A mí me gustaría estar en el equipo frontend. ¿Usaremos socket.io para actualizaciones en vivo? Puedo ayudar también con NodeJS.

**Comment by wcorderolara** [comment]
@patrixd asi es usaremos Node.js y Socket.io para el realtime, asi todo se actualizara en el instante y evitaremos el refresh del navegador, @Jhony0311 cual es tu especialidad?

**Comment by Jhony0311** [comment]
Yo trabajo mas que nada en el front end. Me llevo de maravillas con Backbone, pero Angular tampoco me viene mal. En lo que si diría que soy especialista es en maquetado, HTML y CSS y bueno SPA's es mas que nada lo que siempre hago

**Comment by wcorderolara** [comment]
Excelente @Jhony0311 la verdad me gustaria que implementaramos Angular.js ya que seria algo un poco diferente de lo que se hace en la comunidad pues normalmente utilizam Backbone asi que para variar Angular seria genial jejeje. Saludos

**Comment by Jhony0311** [comment]
Seria genial @WalterC87 sin duda, para este proyecto me parece que lo mejor seria Angular pues está pensado para el real time trabaja mas que bien con sockets asi que concuerdo contigo en el planteamiento. Cuenta con mis habilidades para lo que  salga. Estare mas que encantado de poder trabajar en este proyecto

**Comment by wcorderolara** [comment]
Excelente gracias por tu entusiasmo y apoyo, a partir de mañana estare definiendo los issues para los que quieran empezar apoyarnos los que quieran, ya solo nos falta algun diseñador y estariamos completos para avanzar mas jejeje
